version: "3.6"

services:
  urx:
    container_name: urx
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8080:8080"
      - "8081:8081"
    restart: unless-stopped
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo:5.0
    env_file:
      - ./.env
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
