version: "3.6"

services:
  tinee:
    container_name: tinee
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8080:8080"
      - "8081:8081"
    restart: unless-stopped
    depends_on:
      - mongodb
      - redis

  mongodb:
    container_name: mongodb
    image: mongo:5.0
    env_file:
      - ./.env
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:6.2
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - ./.env
    ports:
      - "6379:6379"

volumes:
  mongodb_data:
