version: "3.6"

services:
  urx:
    container_name: urx
    build: ./
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    command: make start
    restart: unless-stopped
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo:5.0
    env_file:
      - ./.env
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
