name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: golangci-lint
      uses: reviewdog/action-golangci-lint@v2

    - name: Run tests
      run: make test

    - name: Run build
      run: go build ./cmd/urx/main.go

    - name: Trigger deployment script on VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: cd urx && ./deploy.sh
